#!/usr/bin/env python3
"""Class-specific Confidence--Correctness analysis and visualisation.

This module implements the class-specific decomposition used by the
Confidence--Correctness Diagram while delegating the underlying probability-
mass matrices to :mod:`certainty_ratio`.

The module is intentionally classifier-agnostic: it operates only on true
labels, predicted labels and class-probability vectors. It can therefore be
used either on out-of-fold probabilities produced by a validation pipeline or
on probabilities generated by an already fitted classifier.

Notation
--------
``certainty_ratio.py`` uses the matrices ``V`` and ``U`` for decisive/top-1
and residual probability mass, respectively. In the Confidence--Correctness
formulation used by the evaluation pipeline these are exposed as ``H`` and
``L`` to preserve the notation and output schema of pipeline v4::

    H = V = T.T @ Q_plus
    L = U = T.T @ Q_minus

This distinction is important because the scalar/profile symbol ``U`` in the
Confidence--Correctness decomposition denotes *underconfidence*, whereas the
matrix ``U`` in :mod:`certainty_ratio` denotes *residual probability mass*.

For a class ``alpha``, the row-normalised profile is

    R_alpha + O_alpha + U_alpha + A_alpha = 1,

where

- ``R`` (Reliability) is decisive mass assigned to the true class;
- ``O`` (Overconfidence) is decisive mass assigned to a wrong class;
- ``U`` (Underconfidence) is residual mass assigned to wrong classes when the
  top-1 prediction is correct;
- ``A`` (Ambiguity) is residual mass retained by the true class when the top-1
  prediction is wrong.

The plotting routine reproduces the class-specific diagram used by
``confidence_correctness_pipeline.v4.py``: reliability and ambiguity are drawn
on the positive side, while overconfidence and underconfidence are drawn on
the negative side. Each class bar is normalised to unit mass.

Public API
----------
``confidence_correctness_analysis``
    Compute global metrics, class-specific profiles and framework matrices.
``plot_class_confidence_correctness``
    Plot a diagram from a class-specific results DataFrame.
``save_confidence_correctness_diagram``
    Convenience function that computes the profiles and saves the diagram in
    one call.

The implementation deliberately preserves the numerical definitions, column
names, sorting and plotting conventions of pipeline v4 so that pipeline v5 can
produce the same outputs after modularisation.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Iterable, Optional, Sequence, Tuple

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from certainty_ratio import (
    build_confusion_matrix,
    encode_true_labels,
    evaluate_probabilities,
    one_hot,
)


DEFAULT_RELIABILITY_COLOR = "#4AB071"
DEFAULT_AMBIGUITY_COLOR = "#FF4F47"
DEFAULT_OVERCONFIDENCE_COLOR = "#358FA7"
DEFAULT_UNDERCONFIDENCE_COLOR = "#DB8838"


def safe_divide(num: np.ndarray, den: np.ndarray) -> np.ndarray:
    """Divide element-wise, returning zero wherever the denominator is zero.

    This helper matches the behaviour used in pipeline v4 and is kept public
    because it is useful when post-processing class-specific quantities.
    """
    num = np.asarray(num, dtype=float)
    den = np.asarray(den, dtype=float)
    out = np.zeros_like(num, dtype=float)
    mask = den != 0
    out[mask] = num[mask] / den[mask]
    return out


def _prepare_probabilities_like_v4(probabilities: np.ndarray) -> np.ndarray:
    """Clip and row-normalise probabilities.

    `certainty_ratio` module deliberately validates probability matrix strictly. 
    """
    Q = np.asarray(probabilities, dtype=float)
    if Q.ndim != 2:
        raise ValueError("proba must be a two-dimensional probability matrix.")
    if not np.isfinite(Q).all():
        raise ValueError("proba contains NaN or infinite values.")
    Q = np.clip(Q, 0.0, 1.0)
    row_sums = Q.sum(axis=1, keepdims=True)
    if np.any(row_sums <= 0.0):
        raise ValueError("Every probability row must contain positive total mass.")
    return Q / row_sums


def confidence_correctness_analysis(
    y_true: Sequence[Any] | np.ndarray,
    y_pred: Sequence[Any] | np.ndarray,
    proba: np.ndarray,
    classes: Sequence[Any] | np.ndarray,
) -> Tuple[Dict[str, float], pd.DataFrame, Dict[str, np.ndarray]]:
    """Compute global and class-specific Confidence--Correctness quantities.

    Parameters
    ----------
    y_true:
        True class label for each instance.
    y_pred:
        Hard prediction for each instance. The hard confusion matrix and the
        hard sensitivity/precision values are built from these labels, exactly
        as in pipeline. The probability-mass decomposition itself is based
        on the top-1 class of ``proba``.
    proba:
        Probability matrix with shape ``(n_samples, n_classes)``. Columns must
        correspond to ``classes``. Rows are clipped to ``[0, 1]`` and
        normalised before analysis to preserve v4 behaviour.
    classes:
        Global class order corresponding to the columns of ``proba``.

    Returns
    -------
    metrics, class_df, matrices:
        ``metrics`` contains ``acc_star``, ``lambda_h``, ``lambda_l`` and the
        global ``R/O/U/A`` decomposition. ``class_df`` contains class-specific
        contributions, row-normalised profiles and hard/probabilistic
        sensitivity and precision. ``matrices`` contains the same keys and
        notation exported by pipeline v4: ``C``, ``C_star``, ``H``, ``L`` and
        their normalised versions.

    Notes
    -----
    The probability-mass quantities are constructed by
    :func:`certainty_ratio.evaluate_probabilities`. For backward compatibility,
    the decisive matrix ``V`` returned there is exposed here as ``H``, and the
    residual matrix ``U`` is exposed as ``L``.
    """
    class_array = np.asarray(classes)
    y_true_array = np.asarray(y_true)
    y_pred_array = np.asarray(y_pred)
    Q = _prepare_probabilities_like_v4(proba)

    if y_true_array.ndim != 1 or y_pred_array.ndim != 1:
        raise ValueError("y_true and y_pred must be one-dimensional.")
    if len(y_true_array) != len(y_pred_array) or len(y_true_array) != Q.shape[0]:
        raise ValueError("y_true, y_pred and proba must contain the same number of instances.")
    if class_array.ndim != 1 or len(class_array) != Q.shape[1]:
        raise ValueError("classes must contain one label for each probability column.")

    # Core probability-mass mathematics is delegated to certainty_ratio.
    evaluation = evaluate_probabilities(y_true_array, Q, classes=class_array)

    # Preserve v4 semantics for the hard confusion matrix: use the hard labels
    # supplied by the classifier rather than re-deriving them from Q.
    pred_idx, _ = encode_true_labels(y_pred_array, len(class_array), class_array)
    P_hard = one_hot(pred_idx, len(class_array))
    C = build_confusion_matrix(evaluation.T, P_hard)

    C_star = evaluation.CM_star
    H = evaluation.V
    L = evaluation.U

    n = len(y_true_array)
    C_norm = C_star / n
    H_norm = H / n
    L_norm = L / n

    R = float(np.trace(H_norm))
    O = float(H_norm.sum() - np.trace(H_norm))
    A = float(np.trace(L_norm))
    U_under = float(L_norm.sum() - np.trace(L_norm))
    lambda_h = float(H_norm.sum())
    lambda_l = float(L_norm.sum())
    acc_star = float(R + A)

    hard_sens = safe_divide(np.diag(C), C.sum(axis=1))
    hard_prec = safe_divide(np.diag(C), C.sum(axis=0))
    prob_sens = safe_divide(np.diag(C_star), C_star.sum(axis=1))
    prob_prec = safe_divide(np.diag(C_star), C_star.sum(axis=0))

    R_alpha = np.diag(H_norm)
    O_alpha = H_norm.sum(axis=1) - np.diag(H_norm)
    A_alpha = np.diag(L_norm)
    U_alpha = L_norm.sum(axis=1) - np.diag(L_norm)
    row_mass = R_alpha + O_alpha + U_alpha + A_alpha

    class_df = pd.DataFrame({
        "class": class_array,
        "n_class": C.sum(axis=1).astype(int),
        "R_alpha": R_alpha,
        "O_alpha": O_alpha,
        "U_alpha": U_alpha,
        "A_alpha": A_alpha,
        "R_alpha_row_norm": safe_divide(R_alpha, row_mass),
        "O_alpha_row_norm": safe_divide(O_alpha, row_mass),
        "U_alpha_row_norm": safe_divide(U_alpha, row_mass),
        "A_alpha_row_norm": safe_divide(A_alpha, row_mass),
        "hard_sensitivity": hard_sens,
        "hard_precision": hard_prec,
        "prob_sensitivity": prob_sens,
        "prob_precision": prob_prec,
    })
    class_df = class_df.sort_values("R_alpha_row_norm", ascending=False).reset_index(drop=True)

    metrics = {
        "acc_star": acc_star,
        "lambda_h": lambda_h,
        "lambda_l": lambda_l,
        "R": R,
        "O": O,
        "U": U_under,
        "A": A,
        "n_samples": n,
        "n_classes": len(class_array),
    }

    matrices = {
        "C": C,
        "C_star": C_star,
        "H": H,
        "L": L,
        "C_norm": C_norm,
        "H_norm": H_norm,
        "L_norm": L_norm,
    }
    return metrics, class_df, matrices


def plot_class_confidence_correctness(
    class_df: pd.DataFrame,
    title: str,
    output_path: str | Path,
) -> None:
    """Save a class-specific Confidence--Correctness Diagram as PNG.

    Parameters
    ----------
    class_df:
        DataFrame returned by :func:`confidence_correctness_analysis`. The
        columns ``R_alpha_row_norm``, ``O_alpha_row_norm``,
        ``U_alpha_row_norm`` and ``A_alpha_row_norm`` are required.
    title:
        Figure title. Pass an empty string for a diagram without a title.
    output_path:
        Destination PNG path. Parent directories are created automatically.

    Notes
    -----
    Every horizontal bar represents one true class and sums to one in absolute
    mass. Reliability and ambiguity are shown to the right of zero;
    overconfidence and underconfidence are mirrored to the left.
    """
    required = {
        "class",
        "R_alpha_row_norm",
        "O_alpha_row_norm",
        "U_alpha_row_norm",
        "A_alpha_row_norm",
    }
    missing = required.difference(class_df.columns)
    if missing:
        raise ValueError(f"class_df is missing required column(s): {sorted(missing)}")

    data = class_df.copy().sort_values("R_alpha_row_norm", ascending=True)
    y = np.arange(len(data))
    fig_height = max(3.2, 0.42 * len(data) + 1.2)
    fig, ax = plt.subplots(figsize=(11, fig_height))

    R = data["R_alpha_row_norm"].to_numpy()
    O = data["O_alpha_row_norm"].to_numpy()
    U = data["U_alpha_row_norm"].to_numpy()
    A = data["A_alpha_row_norm"].to_numpy()

    ax.barh(y, R, label="Reliability", color=DEFAULT_RELIABILITY_COLOR)
    ax.barh(y, A, left=R, label="Ambiguity", color=DEFAULT_AMBIGUITY_COLOR)
    ax.barh(y, -O, label="Overconfidence", color=DEFAULT_OVERCONFIDENCE_COLOR)
    ax.barh(y, -U, left=-O, label="Underconfidence", color=DEFAULT_UNDERCONFIDENCE_COLOR)

    ax.set_yticks(y)
    ax.set_yticklabels(data["class"].astype(str))
    ax.set_xlim(-1.0, 1.0)
    ticks = np.linspace(-1, 1, 21)
    ax.set_xticks(ticks)
    ax.set_xticklabels([
        f"{abs(t):.1f}" if abs(t) not in (0, 1) else f"{int(abs(t))}"
        for t in ticks
    ])
    ax.axvline(0, linewidth=1.0)
    ax.grid(axis="x", linestyle=":", linewidth=0.7)
    ax.set_title(title)
    ax.legend(loc="lower center", bbox_to_anchor=(0.5, -0.22), ncol=4, frameon=False)
    fig.tight_layout()

    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=300, bbox_inches="tight")
    plt.close(fig)


def save_confidence_correctness_diagram(
    y_true: Sequence[Any] | np.ndarray,
    proba: np.ndarray,
    classes: Sequence[Any] | np.ndarray,
    output_path: str | Path,
    *,
    y_pred: Optional[Sequence[Any] | np.ndarray] = None,
    title: str = "",
) -> Tuple[Dict[str, float], pd.DataFrame, Dict[str, np.ndarray]]:
    """Compute a Confidence--Correctness analysis and save its diagram.

    This convenience interface is useful outside the full experimental
    pipeline. If ``y_pred`` is omitted, hard predictions are taken from the
    top-1 probability in each row, using the same deterministic tie rule as
    :mod:`certainty_ratio`.

    Returns the same ``(metrics, class_df, matrices)`` tuple as
    :func:`confidence_correctness_analysis` so callers can immediately inspect
    or export the underlying quantities.
    """
    class_array = np.asarray(classes)
    Q = _prepare_probabilities_like_v4(proba)
    if y_pred is None:
        evaluation = evaluate_probabilities(y_true, Q, classes=class_array)
        y_pred = class_array[evaluation.predicted_index]

    metrics, class_df, matrices = confidence_correctness_analysis(
        y_true, y_pred, Q, class_array
    )
    plot_class_confidence_correctness(class_df, title, output_path)
    return metrics, class_df, matrices


__all__ = [
    "confidence_correctness_analysis",
    "plot_class_confidence_correctness",
    "save_confidence_correctness_diagram",
    "safe_divide",
]
